spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;database=voll_med_api;loginTimeout=30;TrustServerCertificate=True;
    username: Andrex
    password: andres01
    jpa:
      hibernate:
        ddl-auto: update

  jpa:
    show-sql: true

    properties:
      hibernate:
        format_sql: true

